# DigitalOcean App Platform Configuration
name: mnrec-web
region: sgp

services:
  - name: web
    # Source code
    github:
      repo: moco-batsaikhan/mnrec-web
      branch: main
      deploy_on_push: true

    # Build settings
    build_command: npm run build

    # Run command - CRITICAL для Next.js server mode
    run_command: npm start

    # Environment
    environment_slug: node-js

    # Instance configuration
    instance_count: 1
    instance_size_slug: basic-xxs

    # HTTP settings
    http_port: 3000

    # Health check
    health_check:      http_path: /api/health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

    # Environment variables
    envs:
      - key: NODE_ENV
        value: production
        scope: RUN_TIME

      - key: PORT
        value: "3000"
        scope: RUN_TIME

      # Database credentials - SET THESE IN DIGITALOCEAN DASHBOARD
      - key: DATABASE_HOST
        value: ${db.HOSTNAME}
        scope: RUN_TIME

      - key: DATABASE_PORT
        value: ${db.PORT}
        scope: RUN_TIME

      - key: DATABASE_USER
        value: ${db.USERNAME}
        scope: RUN_TIME

      - key: DATABASE_PASSWORD
        value: ${db.PASSWORD}
        scope: RUN_TIME

      - key: DATABASE_NAME
        value: ${db.DATABASE}
        scope: RUN_TIME

      # JWT Secrets - GENERATE AND SET IN DASHBOARD
      - key: JWT_SECRET
        value: CHANGE_ME_IN_DASHBOARD
        scope: RUN_TIME
        type: SECRET

      - key: REFRESH_TOKEN_SECRET
        value: CHANGE_ME_IN_DASHBOARD
        scope: RUN_TIME
        type: SECRET

    # Routes
    routes:
      - path: /
# Optional: Add managed database
# databases:
#   - name: db
#     engine: MYSQL
#     version: "8"
