CREATE TABLE team (
  id INT AUTO_INCREMENT PRIMARY KEY,
  en_name VARCHAR(128) NOT NULL,
  mn_name VARCHAR(128) NOT NULL,
  en_position VARCHAR(128) NOT NULL,
  mn_position VARCHAR(128) NOT NULL,
  en_description TEXT NOT NULL,
  mn_description TEXT NOT NULL,
  image_url VARCHAR(256),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);